import bcrypt from 'bcryptjs';
const data = {
  users: [
    {
      name: 'Mariah',
      email: 'mariah16265@gmail.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: 'Syeda',
      email: 'syeda@example.com',
      password: bcrypt.hashSync('654321'),
      isAdmin: false,
    },
    {
      name: 'Mariah Abid Masoodi',
      email: 'Mariah16265@gmail.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
  ],
  products: [
    {
      // _id: '1',
      name: 'Foaming Cleanser ',
      slug: 'CeraVe-fomaing-cleasner',
      category: 'SkinCare',
      image: '/images/p1.jpg',
      countInStock: 10,
      price: 74.98,
      brand: 'CeraVe',
      rating: 3.85,
      numReviews: 410,
      description:
        'CeraVe Foaming Facial Cleanser features ceramides, hyaluronic acid, and niacinamide, and is formulated to help to maintain your skin’s protective barrier, lock in moisture, and calm your skin.',
    },
    {
      // _id: '2',
      name: 'Moisturising Lotion',
      slug: 'Cetaphil-mosituirising-lotion',
      category: 'SkinCare',
      image: '/images/p2.jpg',
      countInStock: 10,
      price: 190,
      brand: 'Cetaphil',
      rating: 4.45,
      numReviews: 320,
      description:
        '\n Specially formulated with a dermatologist-backed blend of niacinamide (vitamin B3), panthenol (vitamin B5) and hydrating glycerin to improve the resilience of sensitive skin.',
    },
    {
      // _id: '3',
      name: 'Advanced Night Repair',
      slug: 'estee-lauder-advanced-night-repair',
      category: 'SkinCare',
      image: '/images/p3.jpg',
      countInStock: 10,
      price: 325,
      brand: 'ESTEE LAUDER',
      rating: 4.95,
      numReviews: 650,
      description:
        'Harness the restorative power of night. This deep- and fast-penetrating face serum, with our exclusive Night Peptide, boosts 7 key skin-renewing actions. Reduces the look of multiple signs of aging. Skin looks smoother and less lined, younger, healthier—more radiant and even toned.',
    },
    {
      // _id: '4',
      name: 'Eye Repair Cream',
      slug: 'CeraVe-eye-repair-cream',
      category: 'SkinCare',
      countInStock: 0,
      image: '/images/p4.jpg',
      price: 80,
      brand: 'CeraVe',
      rating: 4.3,
      numReviews: 100,
      description:
        'CeraVe Eye Repair Cream is ophthalmologist-tested and features a non-greasy, fast-absorbing, fragrance-free formula that works to minimize the appearance of dark circles and eye puffiness. ',
    },
    {
      // _id: '4',
      name: 'Samsung Galaxy S22',
      slug: 'Samsung-Galaxy-S22',
      category: 'Electronics',
      countInStock: 8,
      image: '/images/p7.jpg',
      price: 2049,
      brand: 'Samsung',
      rating: 4.1,
      numReviews: 450,
      description:
        'The Samsung Galaxy S22 impresses with its cutting-edge features, powerful performance, and stunning camera capabilities, reaffirming its position as a top-tier flagship smartphone. ',
    },
    {
      // _id: '4',
      name: 'Apple Watch SE',
      slug: 'Apple-Watch-SE',
      category: 'Electronics',
      countInStock: 20,
      image: '/images/p8.jpg',
      price: 799,
      brand: 'Apple',
      rating: 4.6,
      numReviews: 340,
      description:
        'WHY APPLE WATCH SE — All the essentials to help you monitor your fitness, keep connected, track your health, and stay safe. Now up to 20 percent faster, with features like Crash Detection and enhanced workout metrics, it’s a better value than ever.',
    },
    {
      // _id: '4',
      name: 'Samsung 70 Inch TV',
      slug: 'Samsung-70-Inch-TV',
      category: 'Electronics',
      countInStock: 21,
      image: '/images/p10.jpg',
      price: 2189,
      brand: 'Samsung',
      rating: 4.1,
      numReviews: 4339,
      description:
        'Enhanced sense of depth and color.Where gaming comes together. ',
    },
    {
      // _id: '4',
      name: 'Electric Crepe Maker Machine',
      slug: 'Ariete-Crepe-Maker',
      category: 'Electronics',
      countInStock: 119,
      image: '/images/p11.jpg',
      price: 127,
      brand: 'Ariete ',
      rating: 4.1,
      numReviews: 450,
      description:
        'The Crepes Maker Party Time by Ariete transforms your kitchen into a 1950s American Diner, perfect for fun gatherings with family and friends ',
    },
  ],
};
export default data;
