const data = {
  products: [
    {
      name: 'CeraVe Foaming Cleanser ',
      slug: 'CeraVe-fomaing-cleasner',
      category: 'SkinCare',
      image: '/images/p1.jpg',
      price: 74.98,
      brand: 'CeraVe',
      rating: 4.5,
      numReviews: 10,
      description: 'Effective for acne-prone and sensitive skin',
    },
    {
      name: 'Cetaphil Moisturising Lotion',
      slug: 'Cetaphil-mosituirising-lotion',
      category: 'SkinCare',
      image: '/images/p2.jpg',
      price: 190,
      brand: 'Cetaphil',
      rating: 4.5,
      numReviews: 10,
      description: 'Extremely Hydrating',
    },
    {
      name: 'Advanced Night Repair',
      slug: 'estee-lauder-advanced-night-repair',
      category: 'SkinCare',
      image: '/images/p3.jpg',
      price: 325,
      brand: 'ESTEE LAUDER',
      rating: 4.5,
      numReviews: 10,
      description: 'Better than expected',
    },
    {
      name: 'CeraVe Eye Repair Cream',
      slug: 'CeraVe-eye-repair-cream',
      category: 'SkinCare',
      image: '/images/p4.jpg',
      price: 80,
      brand: 'CeraVe',
      rating: 4.5,
      numReviews: 10,
      description: 'My dark circles are gone!',
    },
  ],
};
export default data;
